name: Daily Cron Job


on:
  schedule:
    - cron: '25 11 * * *'   
  workflow_dispatch:      
jobs:
  daily-task:
    runs-on: ubuntu-latest

    steps:
      - name: Display morning message
        run: echo "☀️ Bonjour Clément ! Il est 8h, le workflow s’est exécuté avec succès !"
