name: Daily Cron Job

# Exécution programmée chaque jour à 8h du matin
on:
  schedule:
    - cron: '25 11 * * *'   # Heure UTC (8h UTC = 9h en France l'hiver)
  workflow_dispatch:      # Permet aussi de le lancer manuellement si besoin

jobs:
  daily-task:
    runs-on: ubuntu-latest

    steps:
      - name: Display morning message
        run: echo "☀️ Bonjour Clément ! Il est 8h, le workflow s’est exécuté avec succès !"
