name: Node.js Lint Workflow

# Le workflow se dÃ©clenche sur push ET sur pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      # Ã‰tape 1 : Afficher un message
      - name: Print Hello World
        run: echo "Hello World from GitHub Actions ðŸš€"

      # Ã‰tape 2 : Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Ã‰tape 3 : Installer les dÃ©pendances
      - name: Install dependencies
        run: npm install

      # Ã‰tape 4 : VÃ©rifier le code avec eslint
      - name: Run linter
        run: npm run lint

